apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldtest
  labels:
    app: helloworldtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworldtest
  template:
    metadata:
      labels:
        app: helloworldtest
    spec:
      containers:
      - name: helloworldtest
        image: helloworld:1.0
        ports:
        - containerPort: 7080
