apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldtest-deployment
  labels:
    app: helloworldtest-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworldtest
  template:
    metadata:
      labels:
        app: helloworldtest
    spec:
      containers:
      - name: helloworldtest
        image: helloworld:1.0.5
        ports:
        - containerPort: 8080
