apiVersion: v1
kind: Pod
metadata:
  name: helloworldtest
  labels:
    app: helloworldtest
spec:
  containers:
    - name: helloworldtest
      image: helloworld:1.0
      ports:
        - containerPort: 7080
